const errorCodes = {
  100: "Approved",
  101: "Function Not Available for Selected Issuer",
  200: "Error – API credentials are not valid",
  201: "Error – Invalid Wallet ID",
  202: "Error – Invalid CardIssuerBinID",
  203: "Error – The CardIssuerBinID used is not valid on the WalletID supplied",
  204: "Error – The FirstName is not valid",
  205: "Error – The LastName is not valid",
  206: "Error – The AdrLine1 is not valid",
  207: "Error – The AdrLine2 is not valid",
  208: "Error – The City is not valid",
  209: "Error – The State is not valid",
  210: "Error – The Country is not valid",
  211: "Error – The ZipCode is not valid",
  212: "Error – The PhoneNumber is not valid",
  213: "Error – The Custom1 is not valid",
  214: "Error - The Custom2 is not valid",
  215: "Error - The Custom3 is not valid",
  216: "Error - The Custom4 is not valid",
  217: "Error - The Custom5 is not valid",
  218: "Error – The CardToken is not valid",
  219: "Error – The Amount is invalid",
  220: "Error – The CardToken is not found",
  221: "Error – The Amount to remove from the card is more than the card's current balance.",
  223: "Error – The amount to load is more than the available funds in the wallet",
  224: "Error – Missing Wallet Settings",
  225: "Error – Could not retrieve wallet balance",
  226: "Error – Custom1 is not valid",
  227: "Error – Custom2 is not valid",
  228: "Error – Custom3 is not valid",
  229: "Error – Custom3 needs to be a value between 1 and 4",
  230: "No Transactions found for supplied Card Token",
  231: "Error – Could not update card’s address",
  232: "Error – ProxyNum is required",
  233: "Error – SSN is not valid",
  234: "Error – Cannot find card with proxy number supplied",
  235: "Error – Card number is invalid",
  236: "Error – No cards found with supplied card number",
  237: "Error – WalletName is a required field",
  238: "Error – WalletName is longer than 50 characters",
  239: "Error – Could not find ParentWalletId",
  240: "Error – Could not find the card based on CardToken provided",
  241: "Error – The country is on the restricted list.",
  242: "Error – The WalletIDTo is not a valid number",
  243: "Error – The Description field is required",
  244: "Error – Amount does not appear to be a valid number",
  245: "Error – You can only transfer funds from wallets of the same issuer.",
  246: "Error – There is not enough funds in the WalletIdFrom to cover the amount requested",
  247: "Error – This Issuer does not support this feature",
  248: "Error – Invalid CardStatusId field",
  250: "Error - Invalid CardTypeID",
  251: "Error - CardTypeID must be either 1 or 2",
  252: "Error – The OnCard_FirstName is not valid",
  253: "Error – The OnCard_LastName is not valid",
  254: "Error – The OnCard_AdrLine1 is not valid",
  255: "Error – The OnCard_City is not valid",
  256: "Error – The OnCard_State is not valid",
  257: "Error – The OnCard_CountryIso is not valid",
  258: "Error – The OnCard_ZipCode is not valid",
  259: "Error – The OnCard_PhoneNumber is not valid",
  260: "Error – The ShipTo_FirstName is not valid",
  261: "Error – The ShipTo_LastName is not valid",
  262: "Error – The ShipTo_AdrLine1 is not valid",
  263: "Error – The ShipTo_City is not valid",
  264: "Error – The ShipTo_State is not valid",
  265: "Error – The ShipTo_CountryIso is not valid",
  266: "Error – The ShipTo_ZipCode is not valid",
  267: "Error – The ShipTo_PhoneNumber is not valid",
  268: "Error – The Notif_EmailAdr is not valid",
  269: "Error - Invalid RequestCardID field",
  270: "Error - Could not find record for supplied RequestCardID",
  271: "Error - The OnCard_Email is not valid",
  272: "Error - The OnCard_Gender is not valid",
  273: "Error - The OnCard_DOB is not valid",
  274: "Error - The CardCode is not valid",
  275: "Error - Could not find the CardCode",
  276: "Error - CardNumber does not match to the CardCode",
  277: "Error - Cannot update Card Status",
  278: "Error - Card was already activated",
  279: "Error - The OrderCode is not valid",
  280: "Error - Original PIN is required",
  281: "Error - Start date is not correct",
  282: "Error - End date is not correct",
  283: "Error - The start date is equal to or greater than the end date",
  284: "Error - Unable to request 3D secure check or no active 3D challenges",
  285: "Error - Unable to approve 3D secure check",
  286: "Error - Get PIN function is not supported for this BIN",
  287: "Error - Create PIN function is not supported for this BIN",
  288: "Error - Update PIN function is not supported for this BIN",
  289: "Error - Card is not active",
  290: "Error - TransLimit must be between 0 and 99",
  700: "Address verification failed fraud score",
  701: "Custom5 does not contain a valid ID",
  702: "The KYC ID provided within Custom5 field is not found",
  703: "The KYC ID provided is not Approved",
  800: "Warning - Wallet is locked, please try again",
  801: "Warning - Your account is not authorized to use this function",
  900: "Error - Account related error. Contact support for assistance",
  991: "Error - Could not create PIN",
  992: "Error - Could not update PIN",
  993: "Error - Could not retrieve PIN",
  994: "Error – Could not create sub wallet account",
  995: "Error – Could not remove funds from card",
  996: "Error – Could not fund card",
  997: "Error – Could not retrieve the card balance. Please contact support",
  998: "Error – We were not able to save your card within our db. Please contact support",
  999: "Error – Exception error. Contact support for assistance",
};

// const errorCodes = {
//   100: "Success - Approved",
//   101: "Feature unavailable for selected issuer",
//   200: "Invalid API credentials",
//   201: "Invalid Wallet ID",
//   202: "Invalid CardIssuerBinID",
//   203: "CardIssuerBinID is not valid for the provided WalletID",
//   204: "Invalid First Name",
//   205: "Invalid Last Name",
//   206: "Invalid Address Line 1",
//   207: "Invalid Address Line 2",
//   208: "Invalid City",
//   209: "Invalid State",
//   210: "Invalid Country",
//   211: "Invalid Zip Code",
//   212: "Invalid Phone Number",
//   213: "Invalid Custom1 field",
//   214: "Invalid Custom2 field",
//   215: "Invalid Custom3 field",
//   216: "Invalid Custom4 field",
//   217: "Invalid Custom5 field",
//   218: "Invalid Card Token",
//   219: "Invalid Amount",
//   220: "Card Token not found",
//   221: "Insufficient card balance for this transaction",
//   223: "Insufficient wallet funds",
//   224: "Missing wallet settings",
//   225: "Unable to retrieve wallet balance",
//   226: "Invalid Custom1 value",
//   227: "Invalid Custom2 value",
//   228: "Invalid Custom3 value",
//   229: "Custom3 must be between 1 and 4",
//   230: "No transactions found for this card",
//   231: "Failed to update card address",
//   232: "Proxy number is required",
//   233: "Invalid SSN",
//   234: "No card found for the provided proxy number",
//   235: "Invalid card number",
//   236: "No cards found with this number",
//   237: "Wallet Name is required",
//   238: "Wallet Name exceeds 50 characters",
//   239: "Parent Wallet ID not found",
//   240: "Card not found for the provided CardToken",
//   241: "Country is restricted",
//   242: "Invalid WalletIDTo",
//   243: "Description field is required",
//   244: "Invalid Amount format",
//   245: "Fund transfers are only allowed within the same issuer",
//   246: "Insufficient wallet balance",
//   247: "Feature not supported by this issuer",
//   248: "Invalid CardStatusId",
//   250: "Invalid CardTypeID",
//   251: "CardTypeID must be 1 or 2",
//   252: "Invalid On-Card First Name",
//   253: "Invalid On-Card Last Name",
//   254: "Invalid On-Card Address Line 1",
//   255: "Invalid On-Card City",
//   256: "Invalid On-Card State",
//   257: "Invalid On-Card Country",
//   258: "Invalid On-Card Zip Code",
//   259: "Invalid On-Card Phone Number",
//   260: "Invalid Shipping First Name",
//   261: "Invalid Shipping Last Name",
//   262: "Invalid Shipping Address",
//   263: "Invalid Shipping City",
//   264: "Invalid Shipping State",
//   265: "Invalid Shipping Country",
//   266: "Invalid Shipping Zip Code",
//   267: "Invalid Shipping Phone Number",
//   268: "Invalid Notification Email",
//   269: "Invalid RequestCardID",
//   270: "RequestCardID not found",
//   271: "Invalid On-Card Email",
//   272: "Invalid On-Card Gender",
//   273: "Invalid On-Card Date of Birth",
//   274: "Invalid Card Code",
//   275: "Card Code not found",
//   276: "Card Number does not match the Card Code",
//   277: "Unable to update card status",
//   278: "Card is already activated",
//   279: "Invalid Order Code",
//   280: "Original PIN required",
//   281: "Invalid Start Date",
//   282: "Invalid End Date",
//   283: "Start date must be earlier than the end date",
//   284: "3D secure check failed or unavailable",
//   285: "Unable to approve 3D secure check",
//   286: "Get PIN function not supported for this BIN",
//   287: "Create PIN function not supported for this BIN",
//   288: "Update PIN function not supported for this BIN",
//   289: "Card is not active",
//   290: "Transaction limit must be between 0 and 99",
//   700: "Address verification failed - possible fraud detected",
//   701: "Invalid Custom5 ID",
//   702: "KYC ID not found in Custom5 field",
//   703: "KYC ID is not approved",
//   800: "Wallet is locked, try again later",
//   801: "Account not authorized for this function",
//   900: "Account error - contact support",
//   991: "Unable to create PIN",
//   992: "Unable to update PIN",
//   993: "Unable to retrieve PIN",
//   994: "Failed to create sub-wallet",
//   995: "Failed to remove funds from card",
//   996: "Failed to fund card",
//   997: "Unable to retrieve card balance - contact support",
//   998: "Failed to save card in database - contact support",
//   999: "System error - contact support",
// };

const getErrorResponse = (code) => {
  return errorCodes[code] || "Unknown Error";
};

module.exports = getErrorResponse;
